import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import ProviderNextUi from "./provider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-gradient-to-tr from-slate-900 to-cyan-700 ${inter.className}`}>
        <ProviderNextUi>
          {children}
        </ProviderNextUi>
      </body>
    </html>
  )
}
